### ISSUE TITLE
Launch TODO

### ISSUE THREAD

**Issue by SachaG** [StateOfJS/StateOfCSS-2019#28]
- [x] Favicon 
- [ ] Make data available on Kaggle as json

## Demographics

- [x] Participation by Country: find out why the chart doesn't render
- [ ] Participation by Country: fix units switcher
- [x] Participation by Country: edges are cut off [MOBILE]
- [x] Source Breakdown: make use of `source` hidden field and improve normalization
- [x] Gender Breakdown: fix gap between grid blocks
- [x] Gender Breakdown: Add values inside legends
- [x] Gender Breakdown: Replace with bar chart?
- [x] Source Breakdown (horizontal bar chart): add labels

#### Circle Packing

- [x] Put circles and labels on different layers to avoid overlap
- [x] Think about mobile version of chart
- [x] Add legend inside chart
- [x] Improve tooltips
- [x] Add section labels to chart
- [x] Fix vertical padding on mobile

#### Gauche Chart

- [x] Add pattern to legend for "never heard"

## Technologies

- [x] Use "translated" names for all technologies in all charts

#### Circle Packing

- [x] Put circles and labels on different layers to avoid overlap
- [x] Add section labels to chart
- [x] Think about mobile version of chart
- [x] Improve tooltips

#### Scatterplot

- [x] Add crosshairs (with values?)
- [x] Add labels
- [x] Show interest?

#### Bump Chart

- [x] Use Nivo chart
- [x] Add labels with percentage values

#### Gauche Chart

- [x] Use entity data

#### Heatmaps

- [x] Add salary/experience/etc. heatmaps

## Other Tools

- [x] Handle "other" responses for Text Editors
- [x] Handle "other" responses for Browsers

## Environments

- [x] Handle "other" responses for Browsers
- [x] Handle "other" responses for Form Factors
- [x] Use proper description for browsers question ("Which browsers do you test in?")
- [x] Add print styles question
- [x] Add email CSS question

## Resources

- [x] Handle "other" responses

## Opinions

- [x] Improve design
- [x] Normalize data for "What do developers feel is currently missing from CSS?" question

## Awards

- [x] Fix bug
- [ ] Write content
- [ ] New awards: `most_adopted_feature`, `most_used_resource`, `highest_paying_tool`

## Conclusion

- [x] Write content

**Comment by plouc** [comment]
Environments Browsers/Form factors other responses were to low to be interesting.
